[pytest]

markers = @pytest.mark.put_mythology,
          @pytest.mark.patch_mythology,
          @pytest.mark.get_mythology_id,
          @pytest.mark.get_all_mythology,
          @pytest.mark.delete_mythology_id,
          @pytest.mark.post_mythology


    # Mythos Sandbox API
    put_mythology: Mythos API на обновление mythology
