[pytest]

markers =

# Mythos Sandbox API

    put_mythology: Mythos API на полное обновление mythology
    patch_mythology: Mythos API на частичное обновление mythology
    get_mythology_id: Mythos API на получение mythology по ID
    get_all_mythology: Mythos API на получения списка всех mythology
    delete_mythology_id: Mythos API на удаление mythology по ID
    post_mythology: Mythos API на создание mythology